### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tinoesroho** [rotators/fo2238#1]
The license under which 2238 (specifically, the server-side Angelscript code) was not specified.

Usually projects on Github are released with GPL licensing. However, GPL does not apply to programs that are not redistributed. In simple terms, this means if I make a server based on (if it were GPL) 2238, I would not have to release my modifications to the scripts.

If the intentions of 2238's developers were to provide a solid foundation of mandatory open source so FOnline would flourish, CC-BY-SA may be the best license for their overall work. This mandates that *any* modification ("Derivative Work") be released to the public, and released under the same license, and further, that it credits those whose work it builds on.

**Comment by BartAdv** [comment]
I think our intention was mostly to not let that work to simply vanish (as is the case with many projects, that are not opened) and remain accessible to whomever want to build upon it.

I'm not knowledgeable on the licensing stuff, so I don't even know what license would suit this project best, but, since the code is based on the "original" FOnline codebase, it might be the case it'd have to be the same license.

As far as trying to use the license as the driving force of thriving FOnline games, I doubt it would yield any effect. No one would really be able to enforce it, so anyone wishing to make closed game with this would be able to do so anyway.
